sf: 4
model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpmssl.LatentDiffusionSRTextWTSSL
  params:
    # parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 512
    channels: 4
    cond_stage_trainable: False   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    # for training only
    unfrozen_diff: False
    random_size: False
    time_replace: 1000
    use_usm: False
    #P2 weighting, we do not use in final version
    p2_gamma: ~
    p2_k: ~
    # ignore_keys: []

    sslopt:
      mask_stride: 3
      simself_strategy: 'areaarea_mask_nonlocalavg_cuda_v1'
      kernel_size: 25
      scaling_factor: 0.004
      kernel_size_center: 9
      softmax_sr: True
      softmax_gt: True
      simself_dh: 64
      simself_dw: 64

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModelDualcondV2
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: False
        legacy: False
        semb_channels: 256

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        # for training only
        ckpt_path: xxx # path to VAE model of stablesr
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"

    structcond_stage_config:
      target: ldm.modules.diffusionmodules.openaimodel.EncoderUNetModelWT
      params:
        image_size: 96
        in_channels: 4
        model_channels: 256
        out_channels: 256
        num_res_blocks: 2
        attention_resolutions: [ 4, 2, 1 ]
        dropout: 0
        channel_mult: [ 1, 1, 2, 2 ]
        conv_resample: True
        dims: 2
        use_checkpoint: False
        use_fp16: False
        num_heads: 4
        num_head_channels: -1
        num_heads_upsample: -1
        use_scale_shift_norm: False
        resblock_updown: False
        use_new_attention_order: False


degradation:
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.3, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 15]
  poisson_scale_range: [0.05, 2.0]
  gray_noise_prob: 0.4
  jpeg_range: [60, 95]

  # the second degradation process
  second_blur_prob: 0.5
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.6, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 12]
  poisson_scale_range2: [0.05, 1.0]
  gray_noise_prob2: 0.4
  jpeg_range2: [60, 100]

  gt_size: 512
  no_degradation_prob: 0.01

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: basicsr.data.twostagedegradation_img_mask_dataset.TwoStageDegradation_Img_Mask_Dataset
      params:
        queue_size: 64
        gt_path: ['/home/notebook/code/personal/S9049747/LowLevelLLM/DataSets/SSL_dataset/df2k_ost']
        dataroot_gt_mask: ['/home/notebook/code/personal/S9049747/LowLevelLLM/DataSets/SSL_dataset/df2k_ost_mask']
        face_gt_path: '/home/notebook/code/personal/S9049747/LowLevelLLM/DataSets/SSL_dataset/ffhq10000'
        dataroot_face_gt_mask: '/home/notebook/code/personal/S9049747/LowLevelLLM/DataSets/SSL_dataset/ffhq10000_mask/ffhq10000/Laplacian/L/threshold-20.0/mat'
        num_face: 10000
        crop_size: 512
        io_backend:
          type: disk

        blur_kernel_size_min: 1
        blur_kernel_size_max: 10
        kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob: 0.1
        blur_sigma: [0.2, 1.5]
        betag_range: [0.5, 2.0]
        betap_range: [1, 1.5]

        blur_kernel_size_min2: 1
        blur_kernel_size_max2: 5
        kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
        kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
        sinc_prob2: 0.1
        blur_sigma2: [0.2, 1.0]
        betag_range2: [0.5, 2.0]
        betap_range2: [1, 1.5]

        final_sinc_prob: 0.8

        gt_size: 512
        use_hflip: True
        use_rot: False

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1000

  trainer:
    benchmark: True
    max_steps: 800000
    accumulate_grad_batches: 12

ISSL_loss:
    selfsim_opt:
      type: L1Loss
      loss_weight: !!float 0.5
      reduction: mean
    selfsim1_opt:
      type: KLDistanceLoss
      loss_weight: !!float 0.5
      reduction: mean
      softmax: False
